### ISSUE TITLE
Travis CI tests fail

### ISSUE THREAD

**Issue by andrewgaul** [bouncestorage/swiftproxy#20]
Previous run:

https://travis-ci.org/bouncestorage/swiftproxy/builds/62301501

This is due to using the private fork of the swift repo.  We should change this to a public fork.

@kahing says we have further issues since we use docker-swift as the storage backend which Travis does not support.  We currently do not use the jclouds transient blobstore due to issues with prefix listing.

**Comment by kahing** [comment]
worked around by testing a subset of tests in travis
