### ISSUE TITLE
unable to change aws-s3 default region to other than us-east-1

### ISSUE THREAD

**Issue by mgnethery** [bouncestorage/swiftproxy#63]
I hope I haven't overlooked something obvious, but I can't get swiftproxy to successfully communicate with my aws-s3 bucket. I have the following set in a properties file:

```jclouds.region=ap-southeast-2```

but when I try to access my bucket I get a "400 Bad Request" response. The detail of that response is:

```<Error>
  <Code>AuthorizationHeaderMalformed</Code>
  <Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'ap-southeast-2'</Message>
  <Region>ap-southeast-2</Region>
  <RequestId>3D48B194FD747FCC</RequestId>
  <HostId>EsRZjLox0Khow+U9hT0LLw/J2EdPxNnWYXfpeTRj3SQGQvjPhHsOTrOARwpDCwU81aMVADd8MOs=</HostId>
</Error>```

**Comment by gaul** [comment]
Could you test with 1.2.0-SNAPSHOT?  It include jclouds 2.2.0 which has many fixes, including some related to regions.

**Comment by gaul** [comment]
Actually it appears that Sonatype is down.  You may need to override the dependency manually.

**Comment by gaul** [comment]
OK, pushed to latest to Sonatype.

**Comment by mgnethery** [comment]
I have just tried compiling latest commit. Unfortunately I'm seeing the same behaviour. From the swiftproxy log:
```
D 04-06 23:47:25.999 grizzly-http-server-1 jclouds.headers:56 |::] >> Authorization: AWS4-HMAC-SHA256 Credential=AKxxx.../20200406/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=24c1d680e6fb373f91baa75c59a93d5d2367c77116a35ca69b935a527c899c37
D 04-06 23:47:26.740 grizzly-http-server-1 o.j.h.i.JavaUrlHttpCommandExecutorService:56 |::] Receiving response 1368245670: HTTP/1.1 400 Bad Request
```
The Authorization header is still using `us-east-1`.

**Comment by mgnethery** [comment]
My apologies - I should have thought of this before. I'm able to get around this by specifying the region in the endpoint; so
`jclouds.endpoint=https://s3.ap-southeast-2.amazonaws.com`

I'll close this issue now. Thanks.
